### PR TITLE
Keep original labels in step_discretize

### PR DESCRIPTION
**Pull request by EmilHvitfeldt**
This PR aims to close https://github.com/tidymodels/recipes/issues/674.

It does 2 things
- makes it so when `prefix = NULL` is set in `discretize()`, that the factor levels match what happens in `cut()`. It essentially disable the custom labeling.
- Sets the default value of `prefix` in `discretize()` to `NULL`.

The old behavior is still possible by setting `prefix` to `"bin"`. It think that changing the default is worthwhile since it aligns it better with what happens in the {embed} steps.

``` r
library(recipes)
library(modeldata)
data(biomass)

recipe(HHV ~ carbon, data = biomass) %>% 
  step_discretize(carbon) %>%
  prep() %>%
  bake(new_data = NULL)
#> # A tibble: 536 × 2
#>    carbon        HHV
#>    <fct>       <dbl>
#>  1 (49.7, Inf]  20.0
#>  2 (47.1,49.7]  19.2
#>  3 (47.1,49.7]  18.3
#>  4 (44.7,47.1]  18.2
#>  5 (44.7,47.1]  18.4
#>  6 (44.7,47.1]  18.5
#>  7 (47.1,49.7]  18.7
#>  8 (44.7,47.1]  18.3
#>  9 (47.1,49.7]  18.6
#> 10 (44.7,47.1]  18.9
#> # … with 526 more rows

recipe(HHV ~ carbon, data = biomass) %>% 
  step_discretize(carbon, options = list(prefix = "bin")) %>%
  prep() %>%
  bake(new_data = NULL)
#> # A tibble: 536 × 2
#>    carbon   HHV
#>    <fct>  <dbl>
#>  1 bin4    20.0
#>  2 bin3    19.2
#>  3 bin3    18.3
#>  4 bin2    18.2
#>  5 bin2    18.4
#>  6 bin2    18.5
#>  7 bin3    18.7
#>  8 bin2    18.3
#>  9 bin3    18.6
#> 10 bin2    18.9
#> # … with 526 more rows
```

<sup>Created on 2022-04-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### CODE REVIEW

**Review by topepo — COMMENTED** [review]
This should also add a `keep_original_cols` and error if the prefix is NULL

**Comment by EmilHvitfeldt** [comment]
Which function should error if `prefix = NULL`?

**Comment by topepo** [comment]
if `(keep_original_cols && is.null(prefix)`, the `bake` method should error.

**Comment by EmilHvitfeldt** [comment]
I don't think that `keep_original_cols` fits for this step. I wrote up something a little longer here https://github.com/tidymodels/recipes/issues/929#issuecomment-1067082383. In essence; so far we only used `keep_original_cols` in steps that generate new columns. This step doesn't do that.

**Pull request merged**
