### PR TITLE
Some tools to deal with missing data

### PR DESCRIPTION
**Pull request by alexpghayes**
- `step_indicate()` produces an indicator column that is 1 for `NA` values and 0 otherwise (optionally stripping the original columns from the data)
- `step_sentinel()` converts sentinel values to `NA`. i.e. if -99 indicates missingness, `step_sentinel()` will convert -99 to `NA`

This is really just a first pass, but I'm opening the PR so that I don't forget about this and have it disappear forever. 

Todo:

- [ ] Tests
- [ ] Print methods
- [ ] Built-in sentinel value sets for SAS, SPSS, etc
- [ ] The random i.d. thingy

### CODE REVIEW

**Comment by topepo** [comment]
@alexpghayes I'm working on a release; do you want to finalize this for it?

**Comment by alexpghayes** [comment]
I am drowning in over-commitment; I will have to return this at some future date. I do want to finish it up, it just isn't critical for anything I'm working on ATM.

**Comment by konradsemsch** [comment]
I've been looking for this functionality recently and ended up writing something like this for myself (below). I just installed the development version of recipes but did not see ```step_indicate``` as part of it.  What's the status of releasing this?

```
step_shadow_missing_new <-
  function(terms   = NULL,
           role    = NA,
           skip    = FALSE,
           trained = FALSE,
           prefix  = NULL, 
           columns = NULL) {
    step(
      subclass = "shadow_missing",
      terms    = terms,
      role     = role,
      skip     = skip,
      trained  = trained,
      prefix   = prefix,
      columns  = columns
    )
  }

step_shadow_missing <-
  function(recipe,
           ...,
           role    = NA,
           skip    = FALSE,
           trained = FALSE,
           prefix  = "shadow",
           columns = NULL) {
    add_step(
      recipe,
      step_shadow_missing_new(
        terms   = ellipse_check(...),
        role    = role,
        skip    = skip,
        trained = trained,
        prefix  = prefix,
        columns = columns
      )
    )
  }

prep.step_shadow_missing <- function(x,
                                     training,
                                     info = NULL,
                                     ...) {
  col_names <- terms_select(terms = x$terms, info = info)
  step_shadow_missing_new(
    terms   = x$terms,
    role    = x$role,
    skip    = x$skip,
    trained = TRUE,
    prefix  = x$prefix,
    columns = col_names
  )
}

bake.step_shadow_missing <- function(object,
                                     new_data,
                                     ...) {
  col_names <- object$columns
  for (i in seq_along(col_names)) {
    col <- new_data[[col_names[i]]]
    new_data[, col_names[i]] <- col # the original column should remain
    new_data[, paste0(object$prefix, "_", col_names[i])] <- ifelse(is.na(col), 1, 0) # adding the shadowing column with a prefix
  }
  as_tibble(new_data)
}

print.bake.step_shadow_missing <-
  function(x, width = max(20, options()$width - 30), ...) {
    cat("Creating shadow variables for ", sep = "")
    printer(x$columns, x$terms, x$trained, width = width)
    invisible(x)
  }

tidy.step_shadow_missing <- function(x, ...) {
  if (is_trained(x)) {
    res <- tibble(terms = x$columns)
  } else {
    res <- tibble(terms = sel2char(x$terms))
  }
  res
}

train <-
  data_frame(
    a = c("a", "b", "c"),
    b = c(NA, "d", "e"),
    c = c(NA, "f", "g")
  )

test <-
  data_frame(
    a = c(NA, NA, NA),
    b = c(NA, "d", "e"),
    c = c(NA, "f", "g")
  )

rec <- recipe(train) %>%
  step_shadow_missing(a, b, c) %>%
  prep()

bake(rec, train)
bake(rec, test)
```

**Comment by juliasilge** [comment]
Thank you for your patience @konradsemsch! 🙌 Are you still interested in submitting a new PR with this functionality? 

A few notes, if you are:

- Instead of `remove`, let's use `keep_vars` to align with #462 
- This PR is older, so be mindful of the current state of recipes

**Comment by konradsemsch** [comment]
Hi @juliasilge - yes, definitely! I have most of the code already prepared for that. Let me review and update it a bit and I should be able to push around this weekend :)

**Comment by juliasilge** [comment]
That would be great @konradsemsch! We will look for that new PR from you, and plan to use it to close this older one. 👍

**Comment by konradsemsch** [comment]
Hi @juliasilge. A fresh PR is waiting for your feedback over here: https://github.com/tidymodels/recipes/pull/617.

Looking forward to hearing your thoughts!

**Comment by topepo** [comment]
I'll close this for now

**Pull request closed without merging**
