### PR TITLE
Step woe

### PR DESCRIPTION
**Pull request by Athospd**
step_woe()

It is a transformation_method step that makes woe version of variables. Best suit for nominal variables.

### CODE REVIEW

**Comment by Athospd** [comment]
I just realise that woe has a lot to do with the issue of this chapter http://www.feat.engineering/categorical-supervised-encoding.html

I guess the subject is the same but with different point of view/interpretation.

**Comment by topepo** [comment]
I'm very happy to include this. We do something similar in the `embed` package and I'm thinking that it might be better there. 

I made some changes that were sent to the [`pr/312`](https://github.com/tidymodels/recipes/tree/pr/312) branch. 

It looks good. Some changes that I'd like you to make:

 * Should we produce a new feature for each level of the predictor being encoded? Since `credit_tr$Job` has 4 levels, should there be features `woe_fixed`, `woe_freelance`, `woe_others`, and `woe_partime`?

 * Change the step element `woe_dictionary` to just `dictionary`

 * In the example, bang-bang the dictionary in: `step_woe(Job, Home, outcome = Status, dictionary = !!woe_dict_custom)`; this is a little safer. 

 * Let's do the Bayesian thing and change `odds_offset` to use a [Laplace correction](https://en.wikipedia.org/wiki/Additive_smoothing), which corresponds to a Dirichlet prior. Please change the argument name (for the `\alpha` value) to `Laplace`. 

 * Change the parameter descriptions to start the sentences with capital letters, end with a period, and contains complete sentences (eg. `@param outcome bare name of the binary outcome.` to `@param outcome The bare name of the binary outcome.`)

 * Try to keep your code consistent with the [tidyverse style guide](https://style.tidyverse.org/). I'm not super uptight about this but give it a look. Some things that I changed are [here](https://github.com/tidymodels/recipes/commit/d4589c5547c91d3a5d1b074d040ce547a6838aa8#diff-dc4c30f86d61363cff199327a331830c). 

* When I run the examples, I get this warning "1: Factor `predictor` contains implicit NA, consider using `forcats::fct_explicit_na`". I can usually track those down using `options(warn=2, error = traceback)` but that didn't help. Please take a look for figure out the issue (hopefully without using `forcats`). 

* Does `woe_table()` need to be exported?

**Comment by Athospd** [comment]
Cool! To the points:

> Should we produce a new feature for each level of the predictor being encoded? Since credit_tr$Job has 4 levels, should there be features woe_fixed, woe_freelance, woe_others, and woe_partime?

- About this, I don't have full confidence if I am inside the theory deep enough, but here is my current point of view:

I think it would not be a good practice because the main purpose of woe is to provide a "one real-valued column version" of a given categorical feature. It helps to make sure that the ordinal nature of the categories will be respected inside linear models (among other conveniences). Right?

If this ordinal nature do not exists, then one probably would just be looking for an one hot encoding step, once fitting with `c(0, 0, 1, 1)` is the same as fitting with `c(2.2, 2.2, -1.345, -1.345)`.

Also, if this happen to be needed, what about the explicit

```
df %>%
  step_woe(x, outcome = y) %>%
  step_dummy(woe_x, one_hot = TRUE)

# or 

df %>%
  step_dummy(x, one_hot = TRUE) %>%
  step_woe(starts_with('x_'), outcome = y)
``` 
approach? What do you think?

> Change the step element woe_dictionary to just dictionary

- Done!

> In the example, bang-bang the dictionary in: step_woe(Job, Home, outcome = Status, dictionary = !!woe_dict_custom); this is a little safer.

- I need more instructions here, please. When simply bang-banged the example it do not work. The way "step_woe()" was built, it expects to `dictionary` arg to be a tbl or data.frame. Are you suggesting to rethink this approach?

> Let's do the Bayesian thing and change odds_offset to use a Laplace correction, which corresponds to a Dirichlet prior. Please change the argument name (for the \alpha value) to Laplace.

- Done! Instructive and awesome, btw. From a "ugly workaround" to a full bayesian based feature =). 

> Change the parameter descriptions to start the sentences with capital letters, end with a period, and contains complete sentences (eg. @param outcome bare name of the binary outcome. to @param outcome The bare name of the binary outcome.)

- (kind of) Done. I'd put capital letters and end periods. But english is not my native language so chances are that something is still bit off the standard. Let me know pls.

> Try to keep your code consistent with the tidyverse style guide. I'm not super uptight about this but give it a look. Some things that I changed are here.

- Deal!

> When I run the examples, I get this warning "1: Factor predictor contains implicit NA, consider using forcats::fct_explicit_na". I can usually track those down using options(warn=2, error = traceback) but that didn't help. Please take a look for figure out the issue (hopefully without using forcats).

- I ran all the examples and the tests but wasn't able to reproduce this warning. Do you could tell exactly which example were? And it is funny because I didn't use forcats anywhere too. I'll give a better look anyway!

> Does woe_table() need to be exported?

- I don't think it is necessary neither. Done.

**Comment by topepo** [comment]
I'm running around today and will come back to the first point about the number of columns in a bit...

>> When I run the examples, I get this warning "1: Factor predictor contains implicit NA, consider using forcats::fct_explicit_na". I can usually track those down using options(warn=2, error = traceback) but that didn't help. Please take a look for figure out the issue (hopefully without using forcats).
>
> I ran all the examples and the tests but wasn't able to reproduce this warning. Do you could tell exactly which example were? And it is funny because I didn't use forcats anywhere too. I'll give a better look anyway!

I get them by running `example("step_woe")`. Maybe it is different versions (see below for mine)

```
> sessioninfo::session_info()
─ Session info ─────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.0 (2019-04-26)
 os       macOS High Sierra 10.13.6   
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/New_York            
 date     2019-06-26                  

─ Packages ─────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version     date       lib source                            
 assertthat    0.2.1       2019-03-21 [1] CRAN (R 3.6.0)                    
 class         7.3-15      2019-01-01 [1] CRAN (R 3.6.0)                    
 cli           1.1.0       2019-03-19 [1] CRAN (R 3.6.0)                    
 crayon        1.3.4       2017-09-16 [1] CRAN (R 3.6.0)                    
 dplyr       * 0.8.0.1     2019-02-15 [1] CRAN (R 3.6.0)                    
 generics      0.0.2       2018-11-29 [1] CRAN (R 3.6.0)                    
 glue          1.3.1       2019-03-12 [1] CRAN (R 3.6.0)                    
 gower         0.2.0       2019-03-07 [1] CRAN (R 3.6.0)                    
 ipred         0.9-8       2018-11-05 [1] CRAN (R 3.6.0)                    
 lattice       0.20-38     2018-11-04 [1] CRAN (R 3.6.0)                    
 lava          1.6.5       2019-02-12 [1] CRAN (R 3.6.0)                    
 lubridate     1.7.4       2018-04-11 [1] CRAN (R 3.5.0)                    
 magrittr      1.5         2014-11-22 [1] CRAN (R 3.6.0)                    
 MASS          7.3-51.4    2019-03-31 [1] CRAN (R 3.6.0)                    
 Matrix        1.2-17      2019-03-22 [1] CRAN (R 3.6.0)                    
 nnet          7.3-12      2016-02-02 [1] CRAN (R 3.6.0)                    
 packrat       0.5.0       2018-11-14 [1] CRAN (R 3.6.0)                    
 pillar        1.4.1       2019-05-28 [1] CRAN (R 3.6.0)                    
 pkgconfig     2.0.2       2018-08-16 [1] CRAN (R 3.6.0)                    
 prodlim       2018.04.18  2018-04-18 [1] CRAN (R 3.6.0)                    
 purrr         0.3.2       2019-03-15 [1] CRAN (R 3.6.0)                    
 R6            2.4.0       2019-02-14 [1] CRAN (R 3.6.0)                    
 Rcpp          1.0.1       2019-03-17 [1] CRAN (R 3.6.0)                    
 recipes     * 0.1.5.9000  2019-06-26 [1] local                             
 rlang         0.3.99.9003 2019-06-11 [1] Github (r-lib/rlang@e60f97f)      
 rpart         4.1-15      2019-04-12 [1] CRAN (R 3.6.0)                    
 rstudioapi    0.10        2019-03-19 [1] CRAN (R 3.6.0)                    
 sessioninfo   1.1.1.9000  2019-03-26 [1] Github (r-lib/sessioninfo@dfb3ea8)
 stringi       1.4.3       2019-03-12 [1] CRAN (R 3.6.0)                    
 stringr       1.4.0       2019-02-10 [1] CRAN (R 3.6.0)                    
 survival      2.44-1.1    2019-04-01 [1] CRAN (R 3.6.0)                    
 tibble        2.1.3       2019-06-06 [1] CRAN (R 3.6.0)                    
 tidyselect    0.2.5       2018-10-11 [1] CRAN (R 3.6.0)                    
 timeDate      3043.102    2018-02-21 [1] CRAN (R 3.6.0)                    
 withr         2.1.2       2018-03-15 [1] CRAN (R 3.6.0)                    

[1] /Library/Frameworks/R.framework/Versions/3.6/Resources/library
```
(As an aside: although it can be a major pain, it is a good idea to use the current devel version of `rlang` (and, if you use it, `vctrs`) when doing development. Otherwise, your package might break when a new version gets on CRAN. We try to send out emails to people that are affected but it might be better to see the `rlang` changes as they happen)


>> In the example, bang-bang the dictionary in: step_woe(Job, Home, outcome = Status, dictionary = !!woe_dict_custom); this is a little safer.
>
> I need more instructions here, please. When simply bang-banged the example it do not work. The way "step_woe()" was built, it expects to dictionary arg to be a tbl or data.frame. Are you suggesting to rethink this approach?

Never mind, I was mistaken about it being an issue here. This was my original thinking though: with tidy evaluation, we have to make sure that the object contains the actual argument value (e.g. `woe_dict_custom` here) and not just a _reference_ to a symbol in someone's global environment. If the recipe gets saved to disk then reloaded, the symbol isn't in the global environment anymore. 

This is a problem for the `terms` parts of the recipe steps but not here.

**Comment by Athospd** [comment]
Ok, my setup is up to date now. I reran all the tests and example and I managed to reproduce the warnings.
Fixed it without forcats.

```
- Session info -----------------------------------------------------------------------
 setting  value                       
 version  R version 3.6.0 (2019-04-26)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  Portuguese_Brazil.1252      
 ctype    Portuguese_Brazil.1252      
 tz       America/Sao_Paulo           
 date     2019-06-29                  

- Packages ---------------------------------------------------------------------------
 package     * version    date       lib source                            
 abind         1.4-5      2016-07-21 [1] CRAN (R 3.6.0)                    
 assertthat    0.2.1      2019-03-21 [1] CRAN (R 3.6.0)                    
 backports     1.1.4      2019-04-10 [1] CRAN (R 3.6.0)                    
 class       * 7.3-15     2019-01-01 [1] CRAN (R 3.6.0)                    
 cli           1.1.0      2019-03-19 [1] CRAN (R 3.6.0)                    
 crayon        1.3.4      2017-09-16 [1] CRAN (R 3.6.0)                    
 CVST          0.2-2      2018-05-26 [1] CRAN (R 3.6.0)                    
 ddalpha     * 1.3.9      2019-04-07 [1] CRAN (R 3.6.0)                    
 DEoptimR      1.0-8      2016-11-19 [1] CRAN (R 3.6.0)                    
 dimRed        0.2.3      2019-05-08 [1] CRAN (R 3.6.0)                    
 dplyr       * 0.8.2      2019-06-29 [1] CRAN (R 3.6.0)                    
 DRR           0.0.3      2018-01-06 [1] CRAN (R 3.6.0)                    
 fansi         0.4.0      2018-10-05 [1] CRAN (R 3.6.0)                    
 fastICA       1.2-1      2017-06-12 [1] CRAN (R 3.6.0)                    
 generics      0.0.2      2018-11-29 [1] CRAN (R 3.6.0)                    
 geometry    * 0.4.1      2019-03-27 [1] CRAN (R 3.6.0)                    
 glue          1.3.1      2019-03-12 [1] CRAN (R 3.6.0)                    
 gower       * 0.2.1      2019-05-14 [1] CRAN (R 3.6.0)                    
 ipred       * 0.9-9      2019-04-28 [1] CRAN (R 3.6.0)                    
 kernlab     * 0.9-27     2018-08-10 [1] CRAN (R 3.6.0)                    
 lattice       0.20-38    2018-11-04 [1] CRAN (R 3.6.0)                    
 lava          1.6.5      2019-02-12 [1] CRAN (R 3.6.0)                    
 lubridate   * 1.7.4      2018-04-11 [1] CRAN (R 3.6.0)                    
 magic         1.5-9      2018-09-17 [1] CRAN (R 3.6.0)                    
 magrittr    * 1.5        2014-11-22 [1] CRAN (R 3.6.0)                    
 MASS        * 7.3-51.4   2019-03-31 [1] CRAN (R 3.6.0)                    
 Matrix        1.2-17     2019-03-22 [1] CRAN (R 3.6.0)                    
 nnet          7.3-12     2016-02-02 [1] CRAN (R 3.6.0)                    
 packrat       0.5.0      2018-11-14 [1] CRAN (R 3.6.0)                    
 pillar        1.4.1      2019-05-28 [1] CRAN (R 3.6.0)                    
 pkgconfig     2.0.2      2018-08-16 [1] CRAN (R 3.6.0)                    
 pls           2.7-1      2019-03-23 [1] CRAN (R 3.6.0)                    
 prodlim       2018.04.18 2018-04-18 [1] CRAN (R 3.6.0)                    
 purrr         0.3.2      2019-03-15 [1] CRAN (R 3.6.0)                    
 R6            2.4.0      2019-02-14 [1] CRAN (R 3.6.0)                    
 Rcpp          1.0.1      2019-03-17 [1] CRAN (R 3.6.0)                    
 recipes     * 0.1.5.9000 2019-06-29 [1] local                             
 rlang       * 0.4.0.9000 2019-06-29 [1] Github (r-lib/rlang@fc1aae2)      
 robustbase  * 0.93-5     2019-05-12 [1] CRAN (R 3.6.0)                    
 rpart       * 4.1-15     2019-04-12 [1] CRAN (R 3.6.0)                    
 RSpectra      0.15-0     2019-06-11 [1] CRAN (R 3.6.0)                    
 rstudioapi    0.10       2019-03-19 [1] CRAN (R 3.6.0)                    
 sessioninfo   1.1.1.9000 2019-06-29 [1] Github (r-lib/sessioninfo@193916a)
 sfsmisc     * 1.1-4      2019-05-11 [1] CRAN (R 3.6.0)                    
 stringi       1.4.3      2019-03-12 [1] CRAN (R 3.6.0)                    
 stringr       1.4.0      2019-02-10 [1] CRAN (R 3.6.0)                    
 survival      2.44-1.1   2019-04-01 [1] CRAN (R 3.6.0)                    
 testthat    * 2.1.1      2019-04-23 [1] CRAN (R 3.6.0)                    
 tibble      * 2.1.3      2019-06-06 [1] CRAN (R 3.6.0)                    
 tidyr       * 0.8.3      2019-03-01 [1] CRAN (R 3.6.0)                    
 tidyselect    0.2.5      2018-10-11 [1] CRAN (R 3.6.0)                    
 timeDate      3043.102   2018-02-21 [1] CRAN (R 3.6.0)                    
 utf8          1.1.4      2018-05-24 [1] CRAN (R 3.6.0)                    
 vctrs         0.1.0      2018-11-29 [1] CRAN (R 3.6.0)                    
 withr         2.1.2      2018-03-15 [1] CRAN (R 3.6.0)                    
 zeallot       0.1.0      2018-01-28 [1] CRAN (R 3.6.0)                    

[1] C:/Users/ap_da/OneDrive/Documents/R/win-library/3.6
[2] C:/Program Files/R/R-3.6.0/library
```

**Comment by topepo** [comment]
It looks like there is a reference to `woe_table()` in an example: 

```
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... ERROR
Running examples in ‘recipes-Ex.R’ failed
The error most likely occurred in:
> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: woe_table
> ### Title: Crosstable with woe between a binary outcome and a predictor
> ###   variable.
> ### Aliases: woe_table
> 
> ### ** Examples
> 
> 
> outc <- rep(c("A", "B"), 20)
> pred <- sample(c("X", "Y", "Z", "W"), size = 40, replace = TRUE)
> woe_table(pred, outc)
Error in woe_table(pred, outc) : could not find function "woe_table"
Execution halted
** found \donttest examples: check also with --run-donttest
```

**Comment by Athospd** [comment]
Since `woe_table()` will not be exported, should I just remove the example from doc?

**Comment by topepo** [comment]
Okay. It looks great! I've decided that it belongs in [`embed`](https://github.com/tidymodels/embed) though, given its similarity to the effect encoding bits that are there. Can you create a PR there?

**Comment by Athospd** [comment]
I opened the PR over there! tidymodels/embed#18
Closing here

**Pull request closed without merging**
