### PR TITLE
Fix imputation for all `NA` input

### LINKED ISSUE #689: `step_modeimpute` returns all NA when column is completely null, instead of mode from training data
I'm not sure if this is intended behavior, or if I'm missing some other step that could help me to avoid this issue, but when using a recipe with `step_modeimpute` (this may also apply to other steps – didn't verify) on a factor column, when the column in `new_data` is completely NA, NAs are returned, as opposed to the mode from the training dataset.

```R
df <- data.frame(x = as.factor(c(0, 1, 0)))
binary_features <- 'x'

base_recipe <- recipes::recipe(df) %>%
	update_role(all_of(binary_features), new_role = 'predictor') %>%
	# Impute mode for binary features
	step_modeimpute(one_of(binary_features))

prepped_recipe <- prep(
	base_recipe,
	training = df,
	strings_as_factors = FALSE,
	retain = FALSE,
	fresh = TRUE
)
```

Let's try it out:

```
# Our original data.frame – looks good!
> bake(prepped_recipe, new_data = df)
# A tibble: 3 x 1
  x    
  <fct>
1 0    
2 1    
3 0    
# A new data.frame, with NA, 1, and 0 present. Still looks good – the mode is imputed.
> bake(prepped_recipe, new_data = data.frame(x = as.factor(c(NA, NA, 1, 0))))
# A tibble: 4 x 1
  x    
  <fct>
1 0    
2 0    
3 1    
4 0    
# Another data.frame, this time completely NA. No mode imputed.
> bake(prepped_recipe, new_data = data.frame(x = as.factor(c(NA, NA))))
# A tibble: 2 x 1
  x    
  <fct>
1 NA   
2 NA   
```

This behavior seems strange to me, but then again maybe I'm missing something and there's good reason for this.

### PR DESCRIPTION
**Pull request by juliasilge**
Closes #689 

This PR fixes the 🐛 that we have around imputing on new data that is all `NA`. Here are the new results:

``` r
library(recipes)
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> 
#> Attaching package: 'recipes'
#> The following object is masked from 'package:stats':
#> 
#>     step

df <- data.frame(x1 = c(0, 1, 0),
                 x2 = c(1, 1, 0),
                 x3 = c(0, 1, 1))

rec <- recipe( ~ ., df) %>%
  step_impute_median(all_numeric_predictors()) %>%
  prep()

## always worked
bake(rec, new_data = data.frame(x1 = c(NA, NA, 1, 0, 1),
                                x2 = c(1, 1, 1, NA, 0),
                                x3 = c(0, 1, 1, 0, 0)))
#> # A tibble: 5 x 3
#>      x1    x2    x3
#>   <dbl> <dbl> <dbl>
#> 1     0     1     0
#> 2     0     1     1
#> 3     1     1     1
#> 4     0     1     0
#> 5     1     0     0

## works now
bake(rec, new_data = data.frame(x1 = c(NA, NA),
                                x2 = c(NA, NA),
                                x3 = c(NA, NA)))
#> # A tibble: 2 x 3
#>      x1    x2    x3
#>   <dbl> <dbl> <dbl>
#> 1     0     1     1
#> 2     0     1     1
```

<sup>Created on 2021-06-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

There are problems with all the imputation steps, so I'll be working through them all. Once I started in on these, I found it makes more sense to use vctrs rather than `hardhat::scream()`.

### CODE REVIEW

**Comment by juliasilge** [comment]
Looks like `step_impute_lower()` doesn't need any changes, since it doesn't make much sense to impute below a threshold for `NA`. I did update the tests in the same way for everything else I am doing.

**Comment by juliasilge** [comment]
Closes #704 

Thank you so much @jake-mason for all your help on this! 🙌 If you would like to install this PR and test it out, that would be great:

```r
devtools::install_github("tidymodels/recipes@impute-na-data")
```

**Comment by jake-mason** [comment]
@juliasilge thanks so much for your help with this! Looks great.

**Review by topepo — CHANGES_REQUESTED** [review]
It looks good. Can you add more to the new file about the warning that will be issued for old recipes?

**Pull request merged**
