### PR TITLE
Fixes issue #689 - handler for all-NA `new_data` when using mode impu…

### PR DESCRIPTION
**Pull request by jake-mason**
Fixes issue #689

```R

> library(dplyr)
> set.seed(100)
> 
> df <- data.frame(
+     x = as.factor(c(0, 1, 0, 0)),
+     y = as.factor(c(NA, 1, 1, 0)),
+     z = as.character(c(NA, 'a', 'a', 'b')),
+     a = runif(4),
+     b = c(3, 1, NA, 10)
+ )
> df
  x    y    z         a  b
1 0 <NA> <NA> 0.2046122  3
2 1    1    a 0.3575249  1
3 0    1    a 0.3594751 NA
4 0    0    b 0.6902905 10
> binary_features <- c('x', 'y', 'z')
> continuous_features <- c('a', 'b')
> 
> base_recipe <- recipes::recipe(df) %>%
+     update_role(all_of(binary_features), new_role = 'predictor') %>%
+     # Impute mode for binary features
+     step_impute_mode(all_of(binary_features)) %>%
+     step_impute_median(all_of(continuous_features))
> 
> 
> prepped_recipe <- prep(
+     base_recipe,
+     training = df,
+     strings_as_factors = FALSE,
+     retain = FALSE,
+     fresh = TRUE
+ )
> 
> bake(prepped_recipe, new_data = df)
# A tibble: 4 x 5
  x     y     z         a     b
  <fct> <fct> <fct> <dbl> <dbl>
1 0     1     a     0.205     3
2 1     1     a     0.358     1
3 0     1     a     0.359     3
4 0     0     b     0.690    10
# Factor column `x` completely null
> new_df <- data.frame(
+     x = as.factor(c(NA, NA, NA, NA)),
+     y = as.factor(c(NA, 1, 1, 0)),
+     z = as.character(c(NA, 'a', 'a', 'b')),
+     a = runif(4),
+     b = c(3, 1, NA, 10)
+ )
> bake(prepped_recipe, new_data = new_df)
# A tibble: 4 x 5
  x     y     z         a     b
  <fct> <fct> <fct> <dbl> <dbl>
1 0     1     a     0.358     3
2 0     1     a     0.359     1
3 0     1     a     0.690     3
4 0     0     b     0.536    10
```

### CODE REVIEW

**Comment by jake-mason** [comment]
@topepo @juliasilge first-time contributor, so not sure how the PR process goes. Have you had a chance to look at this one?

**Comment by juliasilge** [comment]
Thank you so much for this PR @jake-mason!! 🙌 

I think we are probably going to want to change the `recipes:::cast()` behavior in the case with `NA` values, rather than handle this in `bake()` like you've outlined here. Max is out on vacation right now but will be back early next week. In the meantime, one thing that would be super helpful would be to add a test to this PR that you/we expect to pass after we address this bug. It should [go in this file](https://github.com/tidymodels/recipes/blob/master/tests/testthat/test_modeimpute.R), I expect.

**Comment by jake-mason** [comment]
Hmmm. Closing this wasn't what I wanted to do. I'll try again with a different PR, I guess.

**Comment by juliasilge** [comment]
What will be most helpful @jake-mason would be a test or two that you expect to pass after we address this bug. We are going to add hardhat and use `hardhat::scream()` instead of the first approach you started with here.

**Pull request closed without merging**
