### PR TITLE
Fixing the broken link to "The R Formula Method: The Good Parts"

### PR DESCRIPTION
**Pull request by doug-friedman**

### CODE REVIEW

**Comment by DavisVaughan** [comment]
Can you please change the Rmd file, and re render the md file using knitr? We do not alter the md files directly

**Comment by doug-friedman** [comment]
🤦‍♂ Sorry about that! Will do.

**Comment by doug-friedman** [comment]
I think I'm all set?

**Comment by DavisVaughan** [comment]
Thank you!

**Pull request merged**
