### PR TITLE
Fixed partial matching on seq args

### PR DESCRIPTION
**Pull request by lgaborini**
When activating warnings on partial argument matching, some annoying messages keep popping up when using recipes:

```
1: In seq.default(along = object$steps) :
  partial argument match of 'along' to 'along.with'
```

This PR should fix them.  
No other changes were made.

### CODE REVIEW

**Comment by topepo** [comment]
The failing tests are solved by updating from master.

**Comment by topepo** [comment]
Also, please add a note to the NEWS file about the change (and your contribution).

**Comment by lgaborini** [comment]
Done, but my PR branch got messed up.  
Should I redo the PR?

**Comment by topepo** [comment]
Thanks!

**Pull request merged**
