### PR TITLE
delete old presentation

### PR DESCRIPTION
**Pull request by EmilHvitfeldt**
This PR will close https://github.com/tidymodels/recipes/issues/811 by deleting the presentation.

### CODE REVIEW

**Comment by hfrick** [comment]
I agree that this should be removed from recipes! but 2017 clearly predates me as well, so: @topepo is that your presentation? should it be moved somewhere else or just deleted?

**Comment by hfrick** [comment]
I agree that this should be removed from recipes! but 2017 clearly predates me as well, so: @topepo is that your presentation? should it be moved somewhere else or just deleted?

**Comment by EmilHvitfeldt** [comment]
The presentation will still be able to be recovered if we merge this PR, you just have to go back to an earlier commit, which we can find by search "presentation" which brings up this PR 😄

**Comment by hfrick** [comment]
right, I was just thinking/remembering the same 👍

**Review by hfrick — APPROVED** [review]

**Pull request merged**
