### PR TITLE
Adding step_cut

### PR DESCRIPTION
**Pull request by EdwinTh**
Took the liberty to create `step_cut` as discussed  #157, because I really needed it myself. Let me know what you think.

### CODE REVIEW

**Comment by topepo** [comment]
Can you look the code over and change some parts to be consistent with the tidyverse style guide? Fir example, the `if` statements in `create_full_breaks` should look like:

```r
create_full_breaks <- function(var, breaks) {
  stopifnot(is.numeric(var), is.numeric(breaks))
  if (min(var) < min(breaks)) {
    breaks <- c(min(var), breaks)
  }
  if (max(var) > max(breaks)) {
    breaks <- c(max(var), breaks)
  }
  sort(breaks)
}
```

Also, please add a `tunable()` method. You might map `breaks` to `dials:::num_breaks()`.

**Comment by EdwinTh** [comment]
Will look into it soon.

**Comment by EdwinTh** [comment]
Just looked into `dial` and `tunable`. I am not sure it is useful to map to `dials:::num_breaks()`, since this `step` is aimed at creating cuts that are meaningful instead of optimizing the number of cuts. 

What I can imagine is that you provide all the possible cuts and that you optimize over which cuts are needed and which not. For example, if you want the cut points only at every decade you provide a grid of, say, six decades and you optimize which decades can be merged. Would that something you can use `dial` and `tunable` with.

**Comment by topepo** [comment]
> Just looked into `dial` and `tunable`. I am not sure it is useful to map to `dials:::num_breaks()`, since this `step` is aimed at creating cuts that are meaningful instead of optimizing the number of cuts. 

Good point. Let's forgo that then.

**Comment by topepo** [comment]
Sorry for the delay on this. Can you update form master?

**Comment by topepo** [comment]
I'll merge. I need to do a release today or tomorrow.

**Comment by EdwinTh** [comment]
Sorry, was a little under the weather last couple of days, could not look into it. Thanks

**Pull request merged**
